---
namespace: ai-agent

resources:
  - templates/namespace.yaml
  - templates/configmap.yaml
  - templates/serviceaccount.yaml
  - templates/rolebinding.yaml
  - templates/pipeline.yaml
  - templates/job.yaml
  - templates/deployment.yaml
  - templates/service.yaml
  - templates/route.yaml
  - templates/secret.yaml
